### ISSUE TITLE
Problems with ECCAIRS 5.1.0.0

### ISSUE THREAD

**Issue by ledsoft** [psiotwo/eccairs-tools#10]
When trying to generate taxonomy for ECCAIRS 5.1.0.0, I noticed a couple of issues:

1. The XML downloaded from ECCAIRS [taxonomy browser](https://e2.aviationreporting.eu/taxonomy) does not have a key, this causes a `NullPointerException` in `EccairsTaxonomyToRdf.transformDictionary`, line 120. A workaround was to manually set some random key in the XML file.
2. Some of the attribute values do not have an explanation, causing a `NullPointerException` in `EccairsTaxonomyToRdf.addTermProperties`, line 272. A workaround is to either edit the XML file or modify source code to check for null explanation value. In particular, it concerns values of attribute with id **1093** (_ERCS Row Score_).
3. Also, apparently, the `TAXONOMY` attribute of element `DICTIONARY` now has a different value pattern (it contains `Eccairs Aviation 5.1.0.0`, but the service probably expects just `Eccairs Aviation` with the version being in the `VERSION` attribute), which messes up the IRI generation. Workaround is again editing the XML file, removing the version part from the `TAXONOMY` attribute.

**Comment by psiotwo** [comment]
They apparently changed the format without changing the taxonomy version. I have another 5.1.0.0 file which goes through correctly.

Anyway, thanks for noticing. Adjusted.
